export const jobs = [
  {
    id: 1,
    color: "rgb(245, 174, 23)",
    logo: "scoot",
    time: "5h ago",
    jobType: "Full time",
    position: "Senior Software Engineer",
    company: "Scoot",
    location: "United Kingdom",
  },
  {
    id: 2,
    color: "rgb(214, 38, 38)",
    logo: "b.",
    time: "20h ago",
    jobType: "Part time",
    position: "Haskel and PureScript Dev",
    company: "Blogr",
    location: "United States",
  },
  {
    id: 3,
    color: "rgb(59, 52, 52)",
    logo: "Vector",
    time: "3d ago",
    jobType: "Part time",
    position: "Midlevel Back End Engineer",
    company: "Vector",
    location: "Russia",
  },
  {
    id: 4,
    color: "rgb(69, 69, 211)",
    logo: "Jagas",
    time: "2d ago",
    jobType: "Full time",
    position: "Senior Application Engineer",
    company: "OfficeLite",
    location: "Jagas",
  },
  {
    id: 5,
    color: "rgb(32, 31, 31)",
    logo: "Pod",
    time: "2d ago",
    jobType: "Part time",
    position: "Remote DevOps Engineer",
    company: "Pod",
    location: "Thailand",
  },
  {
    id: 6,
    color: "rgb(70, 8, 70)",
    logo: "CC",
    time: "4d ago",
    jobType: "Part time",
    position: "Desktop Support Manager",
    company: "Creative",
    location: "Germany",
  },
  {
    id: 7,
    color: "rgb(126, 5, 240)",
    logo: "PD",
    time: "1w ago",
    jobType: "Full time",
    position: "ios Engineer",
    company: "Promodore",
    location: "United States",
  },
  {
    id: 8,
    color: "rgb(8, 102, 245)",
    logo: "MR",
    time: "1w ago",
    jobType: "Full time",
    position: "Senior EJB Developer",
    company: "Maker",
    location: "United Kingdom",
  },
  {
    id: 9,
    color: "rgba(240, 173, 57, 0.788)",
    logo: "CO",
    time: "1w ago",
    jobType: "Part time",
    position: "Senior Frontend Engineer",
    company: "Coff ceastern",
    location: "Singapore",
  },
  {
    id: 10,
    color: "rgb(27, 26, 26)",
    logo: "MC",
    time: "2w ago",
    jobType: "Freelance",
    position: "App & Website Designer",
    company: "MasterCraft",
    location: "United States",
  },
  {
    id: 11,
    color: "rgb(33, 192, 192)",
    logo: "CF",
    time: "1mo ago",
    jobType: "Part time",
    position: "FullStack Developer",
    company: "CrowdFund",
    location: "New Zealand",
  },
  {
    id: 12,
    color: "rgb(214, 123, 38)",
    logo: "TM",
    time: "1mo ago",
    jobType: "Part time",
    position: "Technical Lead Engineer",
    company: "TypeMaster",
    location: "United Kingdom",
  },
];
